- uint:
    name: yellow_team_channel
    min: 0
    max: 16
    value: 0
    description: >-
      The multicast channel to use to communicate with the yellow robots
      in the simulator

- uint:
    name: blue_team_channel
    min: 0
    max: 16
    value: 1
    description: >-
      The multicast channel to use to communicate with the blue robots
      in the simulator
  
- string:
    name: network_interface
    value: "wlp3s0"
    description: >-
      The network interface to use for multicast network communication.
      Can be found using the `ifconfig` command.
  
- string:
    name: vision_ipv4_address
    value: "224.5.23.2"
    description: The IPv4 address to send vision data to
  
- int:
    name: vision_port
    min: 1
    max: 65535
    value: 10020
    description: The port to send vision data to
