include:
  - corner_kick_play_config.yaml
  - goalie_tactic_config.yaml
  - navigator_config.yaml
  - passing_config.yaml
  - robot_navigation_obstacle_factory_config.yaml
  - shoot_goal_tactic_config.yaml
  - shoot_or_pass_play_config.yaml
  - defense_shadow_enemy_tactic_config.yaml
