 - double:
     name: static_field_position_quality_x_offset
     min: 0
     max: 1
     value: 0.3
     description: >-
                The offset from the sides of the field to place the rectangular
                sigmoid we use to determine what areas to pass to
 - double:
     name: static_field_position_quality_y_offset
     min: 0
     max: 1
     value: 0.3
     description: >-
                The offset from the sides of the field to place the rectangular
                sigmoid we use to determine what areas to pass to
 - double:
     name: static_field_position_quality_friendly_goal_distance_weight
     min: 0
     max: 1
     value: 0.3
     description: >-
         The weight that being close to the goal will have on the static
         position quality. Lower, more negative weights result in the distance
         to the goal having less of an effect.
 - double:
     name: enemy_proximity_importance
     min: 0
     max: 10
     value: 1.0
     description: >-
                This controls how heavily we weigh an enemy robot being near the pass
                receiver when calculating enemy risk to a pass
 - double:
     name: ideal_max_rotation_to_shoot_degrees
     min: 0
     max: 180
     value: 60
     description: >-
                The maximum angle that we have to rotate after receiving a pass to
                shoot that we think would likely result in a goal. Note that we may
                try to take shots that require us to rotate more then this, it's more
                of a soft limit.
 - double:
     name: min_pass_speed_m_per_s
     min: 0
     max: 5
     value: 3.8
     description: "The minimum pass speed (in m/s)"
 - double:
     name: max_pass_speed_m_per_s
     min: 0
     max: 10
     value: 5.2
     description: "The maximum pass speed (in m/s)"
 - double:
     name: min_time_offset_for_pass_seconds
     min: 0
     max: 5
     value: 0.7
     description: >-
       Minimum time into the future at which the pass should occur. This is
       to ensure we have enough time to setup a robot to actually perform
       the pass. This is in seconds.
 - double:
     name: max_time_offset_for_pass_seconds
     min: 0
     max: 5
     value: 4.0
     description: >-
       Maximum time into the future at which the pass should occur. This gives the
       upper bound on the pass start time, relative to the current time. This is in
       seconds.
 - double:
     name: enemy_reaction_time
     min: 0
     max: 3.0
     value: 0.2
     description: >-
       How long we think the enemy will take to recognize we're passing and start
       moving to intercept
 - int:
     name: number_of_gradient_descent_steps_per_iter
     min: 0
     max: 100
     value: 2
     description: "The number of steps of gradient descent to perform in each iteration"
 - bool:
     name: debug_rate_pass
     value: false
     description: "Logs the costs that go into rate pass, Robocup 2021 hack that should be removed TODO (#2167)"
