include:
    - corner_kick_play_config.yaml
    - passing_config.yaml
    - enemy_capability_config.yaml
    - ai_config.yaml
    - goalie_tactic_config.yaml
    - defense_shadow_enemy_tactic_config.yaml
    - shoot_or_pass_play_config.yaml
    - attacker_tactic_config.yaml
    - robot_navigation_obstacle_config.yaml
    - defense_play_config.yaml
