AIConfig:
  PassingConfig:
    StaticFieldPositionQualityXOffset:
      min: 0
      max: 1
      default: 0.3
      type: "double"
      description: >-
                 The offset from the sides of the field to place the rectangular
                 sigmoid we use to determine what areas to pass to
    StaticFieldPositionQualityYOffset:
      min: 0
      max: 1
      default: 0.3
      type: "double"
      description: >-
                 The offset from the sides of the field to place the rectangular
                 sigmoid we use to determine what areas to pass to
    StaticFieldPositionQualityFriendlyGoalDistanceWeight:
      min: 0
      max: 1
      default: 0.3
      type: "double"
      description: >-
          The weight that being close to the goal will have on the static
          position quality. Lower, more negative weights result in the distance
          to the goal having less of an effect.
    EnemyProximityImportance:
      min: 0
      max: 10
      default: 0.5
      type: "double"
      description: >-
                 This controls how heavily we weight a robot being near the pass
                 receiver when calculating enemy risk to a pass
    IdealMaxRotationToShootDegrees:
      min: 0
      max: 180
      default: 60
      type: "double"
      description: >-
                 The maximum angle that we have to rotate after receiving a pass to
                 shoot that we think would likely result in a goal. Note that we may
                 try to take shots that require us to rotate more then this, it's more
                 of a soft limit.
    MinPassSpeedMPerS:
      min: 0
      max: 5
      default: 3.5
      type: "double"
      description: "The minimum pass speed (in m/s)"
    MaxPassSpeedMPerS:
      min: 0
      max: 10
      default: 5.5
      type: "double"
      description: "The maximum pass speed (in m/s)"
    MinTimeOffsetForPassSeconds:
      min: 0
      max: 5
      default: 0.7
      type: "double"
      description: >-
        Minimum time into the future at which the pass should occur. This is
        to ensure we have enough time to setup a robot to actually perform
        the pass. This is in seconds.
    MaxTimeOffsetForPassSeconds:
      min: 0
      max: 5
      default: 4.0
      type: "double"
      description: >-
        Maximum time into the future at which the pass should occur. This gives the
        upper bound on the pass start time, relative to the current time. This is in
        seconds.
    EnemyReactionTime:
      min: 0
      max: 3.0
      default: 0.4
      type: "double"
      description: >-
        How long we think the enemy will take to recognize we're passing and start
        moving to intercept
    NumPassesToOptimize:
      min: 1
      max: 1000
      default: 15
      type: "int"
      description: "The number of passes to try to optimize at any given time"
    NumPassesToKeepAfterPruning:
      min: 0
      max: 1000
      default: 3
      type: "int"
      description: "The number of passes to keep after pruning"
    NumberOfGradientDescentStepsPerIter:
      min: 0
      max: 1000
      default: 10
      type: "int"
      description: "The number of steps of gradient descent to perform in each iteration"
    PassEqualityMaxPositionDifferenceMeters:
      min: 0
      max: 4
      default: 0.05
      type: "double"
      description: >-
        The maximum allowed difference between the receiver and passer
        point of two passes for which they are considered equal
    PassEqualityMaxStartTimeDifferenceSeconds:
      min: 0
      max: 3
      default: 0.1
      type: "double"
      description: "TODO: Add description as part of #149"
    PassEqualityMaxSpeedDifferenceMetersPerSecond:
      min: 0
      max: 4
      default: 0.3
      type: "double"
      description: "TODO: Add description as part of #149"

  NavigatorConfig:
    TransitionSpeedFactor:
      min: 0
      max: 1
      default: 0.6
      type: "double"
      description: "Factor of max speed to use for transition speed calculations"
    EnemyRobotProximityLimit:
      min: 0
      max: 10.0
      default: 2.0
      type: "double"
      description: "Distance to nearest robot when we stop slowing down to avoid collisions"

  RobotNavigationObstacleFactoryConfig:
    SpeedScalingFactor:
      min: 0.0
      max: 1.0
      default: 0.2
      type: "double"
      description: >-
        The factor to multiply object speed by to determine the length of the velocity
        obstacle in the objects direction of travel.
    RobotObstacleInflationFactor:
      min: 0
      max: 10
      default: 2.0167
      type: "double"
      description: "Factor for robot obstacle size"

  GoalieTacticConfig:
    GoalieFinalSpeed:
        min: 0.0
        max: 3.0
        default: 0.0
        type: "double"
        description: >-
          Control the final speed of the goalie to be able to intercept shots better
    BallSpeedPanic:
        min: 0.0
        max: 6.0
        default: 0.2
        type: "double"
        description: >-
          At what speed of the ball should the goalie panic and stop the ball
    BlockConeRadius:
        min: 0.0
        max: 1.0
        default: 0.3
        type: "double"
        description: >-
            The radius to wedge the robot into the cone, defaults to MAXROBOTRADIUS
    DefenseAreaDeflation:
        min: 0.1
        max: 0.5
        default: 0.2
        type: "double"
        description: >-
          How much to deflate the defense area by, larger value means closer to the
          net
  ShootGoalTacticConfig:
    EnemyAboutToStealBallRectangleWidth:
        min: 0.0
        max: 2.0
        type: "double"
        default: 0.18
        description: >-
            The total width ('sideways' of the robot) of the rectangle starting
            from the friendly robot inside which we think an enemy is about to
    EnemyAboutToStealBallRectangleExtensionLength:
        min: 0.0
        max: 2.0
        type: "double"
        default: 0.27
        description: >-
            The total length (in the direction the robot is facing) of the rectangle
            starting from the friendly robot inside which we think an enemy is about to
            steal the ball
  DefenseShadowEnemyTacticConfig:
    BallStealSpeed:
      default: 0.3
      max: 1.0
      min: 0.0
      type: "double"
      description: Try to steal the passee's ball below this ball speed
  CornerKickPlayConfig:
    MaxTimeCommitToPassSeconds:
      min: 0.0
      max: 5.0
      default: 3.0
      type: "double"
      description: The maximum time that we will wait before committing to a pass
  ShootOrPassPlayConfig:
    AbsMinPassScore:
      min: 0.0
      max: 1.0
      default: 0.05
      type: double
      description: The absolute minimum pass quality we're willing to attempt
    PassScoreRampDownDuration:
      min: 0.0
      max: 5.0
      default: 2.0
      type: double
      description: >-
        When we're choosing a pass, we start by looking for a pass with a perfect score
        of 1, and then over time lower the score we're will to accept. This parameter
        how fast we ramp down to absMinPassScore. This is in seconds.
    MinOpenAngleForShotDeg:
      min: 0.0
      max: 90.0
      default: 6
      type: double
      description: The minimum open angle to the goal that we require before taking a shot
