 HandheldControllerConfig:
  RobotId:
    min: 0
    max: 32
    default: 0
    type: "int"
    description: "The ID of the robot being controller by the game controller"
  KickSpeedMetersPerSecond:
    min: 0.0
    max: 6.5
    default: 4.0
    type: "double"
    description: "The robot's kick speed in meters per second"
  ChipDistanceMeters:
    min: 0.0
    max: 5.0
    default: 1.0
    type: "double"
    description: "How far in meters the robot will chip"
  DribblerRpm:
    min: 0
    max: 10000
    default: 1000
    type: "int"
    description: "The RPM of the robot's dribbler when turned on"
  MaxLinearSpeed:
    min: 0.0
    max: 3.0
    default: 1.0
    type: "double"
    description: "The max allowed linear speed of the robot in m/s"
  MaxAngularSpeed:
    min: 0.0
    max: 12.0
    default: 6.0
    type: "double"
    description: "The max allowed angular speed of the robot, in rad/s"
  DevicePath:
    type: "std::string"
    default: "/dev/input/js0"
    description: "The filepath to the controller on the system"
