AI:
  vision_flipping_filter_enabled:
    type: "bool"
    default: true
    description: Ignores frames if our goalie appears in the opponent defense area
  run_ai:
    type: "bool"
    default: true
    description: >-
        Selecting will allow HL and Navigator to run, unselecting will
        stop new decisions from being made, but the robots will finish
        the last commands they were given. DO NOT USE in place of the e-stop.
  override_ai_play:
    type: "bool"
    default: false
    description: >-
        Overrides the current play with the play
        specified by current_play parameter
  current_ai_play:
    type: "std::string"
    default: "Example Play"
    options:
        - "Example Play"
        - "Stop Play"
        - "Halt Play"
        - "Corner Kick Play"
        - "Free Kick Play"
        - "Defense Play"
        - "KickoffEnemy Play"
        - "KickoffFriendly Play"
        - "Enemy Freekick Play"
        - "Penalty Kick Play"
        - "Penalty Kick Enemy Play"
        - "ShootOrChip Play"
    description: >-
        Specifies the ai play that should be in use
  refbox:
    override_refbox_play:
      type: "bool"
      default: false
      description: >-
          Overrides the current refbox play with the play
          specified by current_play parameter
    current_refbox_play:
      type: "std::string"
      default: "Halt"
      description: >- 
          Specifies the refbox play that should be in use
    override_refbox_defending_side:
      type: "bool"
      default: true
      description: >-
          Overrides the defending side provided by refbox, 
          with defending_positive_side parameter
    defending_positive_side:
      type: "bool"
      default: true
      description: >-
          Positive if selected, Negative if unselected
    override_refbox_friendly_team_color:
      type: "bool"
      default: true
      description: >-
          Overrides the team color provided by refbox, 
          with friendly_color_yellow parameter
    friendly_color_yellow:
      type: "bool"
      default: true
      description: >-
          Yellow if selected, Blue if unselected
    friendly_goalie_id:
      type: "int"
      min: 0
      max: 16
      default: 0
      description: >-
        The id of the friendly goalie
    enemy_goalie_id:
      type: "int"
      min: 0
      max: 16
      default: 0
      description: >-
        The id of the enemy goalie
    ignore_invalid_camera_data:
      type: "bool"
      default: false
      description: >-
        Whether or not to ignore invalid camera data. If this value is true, any ball or robot detections that are not
        within the min and max valid x coordinates will be ignored. If this value is false, all data is collected as
        normal and not ignored.
    min_valid_x:
      type: "double"
      min: -10.0
      max: 10.0
      default: -10.0
      description: >-
        When ignore_invalid_camera_data is true, any robot or ball detection with an x-coordinate less than this value
        is ignored.
    max_valid_x:
      type: "double"
      min: -10.0
      max: 10.0
      default: 10.0
      description: >-
        When ignore_invalid_camera_data is true, any robot or ball detection with an x-coordinate greater than this
        value is ignored.
