---
- name: Deploy to the powerboard
  hosts: THUNDERBOTS_HOSTS

  tasks:
    - name: Sync powerboard files
      become: true
      become_method: ansible.builtin.sudo
      ansible.posix.synchronize:
        src: ../../../../../power/powerloop.tar.gz
        dest: ~/
        recursive: true
        copy_links: true

    - name: Untar powerboard files
      ansible.builtin.shell: "mkdir -p powerloop && tar -xvf ~/powerloop.tar.gz -C powerloop"
      register: result
      changed_when: true
      args:
        chdir: ~/

    - name: Put the powerboard in bootloader mode
      ansible.builtin.pause:
        prompt: "Press enter to continue"
        echo: false

    - name: Flashing... (this will take a while on the first run)
      ansible.builtin.command: "/opt/tbotspython/bin/platformio run --disable-auto-clean -t nobuild -t upload -d ~/powerloop/host/bin/software/power"
      register: result
      changed_when: true

    - name: Reset powerboard to finish flashing
      ansible.builtin.pause:
        prompt: "Press enter to continue"
        echo: false
